#!/usr/bin/env bash
# debugging nginx port 80
#rm /etc/nginx/sites-enabled/default
#Configure nginx to listen on port 80 for all active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart
